/*
 Online Page Editor Add-on
 Version: 1.2.3
 (c) 2013 DMXzone.com
 @build 03-07-2013 18:37:56
*/
(function(a){var B={actionUrl:"dmxPageEditor.asp",activationMethod:"key",activationKey:"ctr+shft+@",activationSelector:"",editDreamweaverRegions:!0,editableRegionsList:"",securityMethod:"user"};a.fn.dmxPageEditor=function(f){function n(){if("file:"==document.location.protocol)alert("Can not run Online Page Editor from local file!\nPlease run this page through a web server!");else if(0<a(".dmxActivator").length||g)u(),a(".dmxActivator").each(function(){a(".dmxPageEditorIcons .dmxPageEditorIconsBottom",
this).remove()}).removeClass("dmxActivator"),a(document).off("click.dmxPageEditor",".dmxPageEditorIcons,.dmxPageEditorIconsBottom"),a.ajax({type:"GET",url:i+"?auth=login&action=logoff"});else if("login"==c.securityMethod){var d=b("dmxAuthorization");d?a.ajax({type:"POST",url:i+"?auth=login",data:{authorization:d},success:function(a){"LOGIN OK"==a?k():l()}}):l()}else a.ajax({url:i+(""!=m?"?"+m:""),success:function(){k()},error:function(a){401==a.status||400==a.status?alert("Access denied!"):404==a.status&&
alert("Can not execute ScriptLibrary/"+c.actionUrl+"\nFile is missing or "+v()+" is not supported on this server!")}})}function l(d){require([h+"jquery.simplemodal.min.js",h+"jquery.crypt.js"],function(){a.modal('<div id="dmxPageEditorLogin_status">\n<h1>LOGIN</h1><div id="login_response"></div>\n<form id="login" action="">\n<label>Username</label><input type="text" class="txtfield" id="dmx_login_username" name="username"><br />\n<label>Password</label><input type="password" class="txtfield" id="dmx_login_password" name="password"><br />\n<label>&nbsp;</label><input value="Login" name="Login" id="dmxPageEditorLogin_submit" type="submit" />\n<div id="ajax_loading"><img align="absmiddle" src="'+
o+'dmxPageEditor/spinner.gif">&nbsp;Processing...</div>\n</form></div>\n',{containerId:"dmxPageEditorLogin",onClose:function(){""==p&&""==q&&a.ajax({type:"GET",url:i+"?auth=login&action=logoff"});a.modal.close()}});a("#dmxPageEditorLogin_status > form").submit(function(){a("#dmxPageEditorLogin_submit").hide();a("#ajax_loading").show();a.ajax({type:"GET",url:i+"?auth=login&action=token",success:function(c){r=c;c={authorization:a().crypt({method:"md5",source:"username:"+a("#dmx_login_username").val()+
":password:"+a("#dmx_login_password").val()+":"+r})};a.ajax({type:"POST",url:i+"?auth=login",data:c,success:function(c){a("#dmxPageEditorLogin_submit").show();a("#ajax_loading").hide();"LOGIN OK"==c?(p=a("#dmx_login_username").val(),q=a("#dmx_login_password").val(),a.modal.close(),d?d.call(this):k()):a("#login_response").html(c)},error:function(d,c,j){a("#login_response").html(j)}})},error:function(d,c,b){a("#login_response").html(b)}});return!1})})}function b(a){var c="",b;if(document.cookie)for(var g=
[],g=document.cookie.split("; "),j=0;j<g.length;j++)b=g[j].split("="),b[0]==a&&(c=2<=b.length?unescape(b[1]):"");return c}function k(){function d(f,x){g.html(f.html);var e={page:y,name:g[0].id,html:f.html,type:g.hasClass("dmxActivatorDiv")?"div":"region"};if("login"==c.securityMethod){var j=b("dmxAuthorization");e.authorization=j&&!x?j:a().crypt({method:"md5",source:"username:"+p+":password:"+q+":"+r})}a.ajax({type:"POST",url:i+"?action=save"+(""!=m?"&"+m:""),data:e,success:function(a){var c=a.indexOf("ERROR: [");
if(-1!=c){var b=a.indexOf("]",c+9);alert("Server Error:\n"+a.substring(c+8,b))}else"Invalid login!"==a?x?l(function(){d(f)}):d(f,!0):(alert("Save successful!"),u(),window.location.reload(!0))},error:function(a,d,b){401==a.status||400==a.status?alert("Access denied!"):500==a.status?(d=a.responseText,b=d.indexOf("ERROR: ["),-1!=b?(a=d.indexOf("]",b+9),alert("Server Error:\n"+d.substring(b+8,a))):alert("Server Error, response:\n"+a.responseText)):404==a.status?alert("Can not execute ScriptLibrary/"+
c.actionUrl+"\nFile is missing or "+v()+" is not supported on this server!"):alert("Error "+b+", code: "+a.status)}})}z?e():(require([h+"dmxEditor.min.js",h+"css.js!"+o+"dmxEditor.css",h+"jquery.crypt.js"],function(){z=!0;e()}),a("body").bind("editor:afterSave",function(a,c){d(c)}),a("body").bind("editor:removed",function(){g&&(s(g),g=null)}))}function e(){if(""!=c.editableRegionsList){var d=("#"+c.editableRegionsList.replace(/\s*,\s*/gi,",#")).replace(/##/gi,"#");s(a(d).addClass("dmxActivatorDiv"))}c.editDreamweaverRegions&&
s(a("body").getEditableRegions());a(document).on("click.dmxPageEditor",".dmxPageEditorIcons,.dmxPageEditorIconsBottom",function(){w(this)})}function v(){return"dmxPageEditor.asp"==c.actionUrl?"ASP":"PHP"}function s(d){d&&d.addClass("dmxActivator").each(function(){var d=a(this).offset();a(this).prepend('<div class="dmxPageEditorIcons'+(22>d.top?"Bottom":"")+'"><img src="'+o+'dmxEditor/pencil.png" alt="Click to edit this region" title="Click to edit this region" /></div>')})}function w(d,f){if(g){var e=
g.data("dmxEditor");if(e&&e.isDocumentModified()&&confirm("The previous editable area is not saved yet. Changes will be lost if you don't save.\nDo you want to save first?")){e.save();return}u()}e=a(d).parent();e={page:y,name:e[0].id,type:e.hasClass("dmxActivatorDiv")?"div":"region"};if("login"==c.securityMethod){var h=b("dmxAuthorization");e.authorization=h&&!f?h:a().crypt({method:"md5",source:"username:"+p+":password:"+q+":"+r})}a.ajax({type:"POST",url:i+"?action=load"+(""!=m?"&"+m:""),data:e,success:function(b){var e=
b.indexOf("ERROR: [");if(-1!=e){var h=b.indexOf("]",e+9);alert("Server Error:\n"+b.substring(e+8,h))}else"LOGIN OK"==b?alert("You have an old version of the Page Editor Server files! Please reapply it on the page!"):"Invalid login!"==b?f?l(function(){w(d)}):w(d,!0):(g=a(d).parent(),a(d).remove(),g.removeClass("dmxActivator"),c.editorConfig.content=b,g.dmxEditor(c.editorConfig))},error:function(a,d,b){401==a.status||400==a.status?alert("Access denied!"):500==a.status?(d=a.responseText,b=d.indexOf("ERROR: ["),
-1!=b?(a=d.indexOf("]",b+9),alert("Server Error:\n"+d.substring(b+8,a))):alert("Server Error, response:\n"+a.responseText)):404==a.status?alert("Can not execute ScriptLibrary/"+c.actionUrl+"\nFile is missing or "+v()+" is not supported on this server!"):alert("Error "+b+", code: "+a.status)}})}function u(){if(g){var a=g.data("dmxEditor");a&&a.destruct();s(g);g=null}}var c=a.extend(!0,{},B,f);c.editorConfig||(c.editorConfig={});a.extend(!0,c.editorConfig,{width:"100%",autoSaveInterval:0,autoIncludeCss:!0,
toolbars:{Common:{items:{save:!0,close:!0}}},extensions:c.editorConfig.extensions?a.merge(["autosize"],c.editorConfig.extensions):["autosize"]});var z=!1,h;h=(f=a("script[src$='dmxPageEditor.js']"))&&0<f.length?f[0].src.replace(/dmxPageEditor\.js$/i,"").replace(/\s+/g,"%20"):"";var o,f="/styles",A=a('link[href*="dmxPageEditor.css"]');0<A.length&&(f=A[0].href.replace(/dmxPageEditor\.css$/i,""));o=f;c.currentPage?f=c.currentPage:(f=h.replace(/\/ScriptLibrary\/?$/i,""),f=document.location.href.replace(f,
""));var y=f,m="user"==c.securityMethod?"auth=user":"login"==c.securityMethod?"auth=login":"",r="",p="",q="",i=h+c.actionUrl,g;if("key"==c.activationMethod&&""==c.activationSelector){var t;switch(c.activationKey){case "ctr+shft+@":t=function(a){return(a.ctrlKey||a.metaKey)&&a.shiftKey&&a.which==50};break;case "ctr+f2":t=function(a){return(a.ctrlKey||a.metaKey)&&a.which==113};break;case "ctr+\\":t=function(a){return(a.ctrlKey||a.metaKey)&&a.which==220}}a(document).keydown(function(a){if(t(a)){n();
a.preventDefault()}})}else a(document).on("click.dmxPageEditor",c.activationSelector,function(a){n();a.preventDefault()});a(window).load(function(){b("dmxPageEditorActive")!=""&&n()})};a.fn.getEditableRegions=function(){var f=a([]);this.each(function(n,l){for(var b=l.firstChild;b;){if(8===b.nodeType){if(-1!=b.data.indexOf("InstanceBeginEditable")){var k=a(),e=b.data.match(/name="([^"]*)"/),e=e&&0<e.length?e[1]:"editor1",b=b.nextSibling;if(!("DIV"==b.nodeName&&b.id==e)){for(;b&&!(8==b.nodeType&&-1!=
b.data.indexOf("InstanceEndEditable"));)k.push(b),b=b.nextSibling;k.wrapAll('<div id="'+e+'" class="dmxEditor" style="width:100%" />')}}}else 1===b.nodeType&&(f=f.add(a(b).getEditableRegions()));b=b.nextSibling}});return a(".dmxEditor")}})(jQuery);